addSbtPlugin("org.typelevel"    % "sbt-tpolecat"      % "0.5.3")
addSbtPlugin("ch.epfl.scala"    % "sbt-scalafix"      % "0.12.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"       % "2.5.2")
addSbtPlugin("org.wartremover"  % "sbt-wartremover"    % "3.5.6")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"      % "2.4.4")
addSbtPlugin("com.github.sbt"  % "sbt-dynver"         % "5.1.0")
